INSERT INTO EMPLOYEE (EMPLOYEE_NAME,EMPLOYEE_DEPARTMENT,EMPLOYEE_DESIGNATION,EMPLOYEE_LOCATION,EMPLOYEE_MOBILE_NO,EMPLOYEE_EMAIL_ID,EMPLOYEE_GENDER,EMPLOYEE_SALARY)
VALUES("Saikumar","HR","Software Engineer","HYD","7306711886","saikumar@gmail.com","Male","30000");

INSERT INTO EMPLOYEE (EMPLOYEE_NAME,EMPLOYEE_DEPARTMENT,EMPLOYEE_DESIGNATION,EMPLOYEE_LOCATION,EMPLOYEE_MOBILE_NO,EMPLOYEE_EMAIL_ID,EMPLOYEE_GENDER,EMPLOYEE_SALARY)
VALUES("Sriveni","HR","Software Engineer","HYD","9390462537","sriveni@gmail.com","Female","30000");

INSERT INTO EMPLOYEE (EMPLOYEE_NAME,EMPLOYEE_DEPARTMENT,EMPLOYEE_DESIGNATION,EMPLOYEE_LOCATION,EMPLOYEE_MOBILE_NO,EMPLOYEE_EMAIL_ID,EMPLOYEE_GENDER,EMPLOYEE_SALARY)
VALUES("Sita","HR","Senior Software Engineer","BLR","9390584040","sita@gmail.com","Female","65000");

INSERT INTO EMPLOYEE (EMPLOYEE_NAME,EMPLOYEE_DEPARTMENT,EMPLOYEE_DESIGNATION,EMPLOYEE_LOCATION,EMPLOYEE_MOBILE_NO,EMPLOYEE_EMAIL_ID,EMPLOYEE_GENDER,EMPLOYEE_SALARY)
VALUES("Sriram","HR","Senior Software Engineer","PUNE","9948489885","sriram@gmail.com","Male","70000");

INSERT INTO EMPLOYEE (EMPLOYEE_NAME,EMPLOYEE_DEPARTMENT,EMPLOYEE_DESIGNATION,EMPLOYEE_LOCATION,EMPLOYEE_MOBILE_NO,EMPLOYEE_EMAIL_ID,EMPLOYEE_GENDER,EMPLOYEE_SALARY)
VALUES("Nikitha","HR","Manager HR Dept","HYD","8978065339","nikhitha@gmail.com","Female","90000");

INSERT INTO EMPLOYEE (EMPLOYEE_NAME,EMPLOYEE_DEPARTMENT,EMPLOYEE_DESIGNATION,EMPLOYEE_LOCATION,EMPLOYEE_MOBILE_NO,EMPLOYEE_EMAIL_ID,EMPLOYEE_GENDER,EMPLOYEE_SALARY)
VALUES("Vinod","WPS","System Analyst","BLR","7863749023","vinod@gmail.com","Male","20000");

INSERT INTO EMPLOYEE (EMPLOYEE_NAME,EMPLOYEE_DEPARTMENT,EMPLOYEE_DESIGNATION,EMPLOYEE_LOCATION,EMPLOYEE_MOBILE_NO,EMPLOYEE_EMAIL_ID,EMPLOYEE_GENDER,EMPLOYEE_SALARY)
VALUES("Praveen","WPS","System Analyst","BLR","9876543210","praveen@gmail.com","Male","22000");

INSERT INTO EMPLOYEE (EMPLOYEE_NAME,EMPLOYEE_DEPARTMENT,EMPLOYEE_DESIGNATION,EMPLOYEE_LOCATION,EMPLOYEE_MOBILE_NO,EMPLOYEE_EMAIL_ID,EMPLOYEE_GENDER,EMPLOYEE_SALARY)
VALUES("Sridhar","WPS","Senior System Analyst","HYD","7654321090","sridhar@gmail.com","Male","40000");

INSERT INTO EMPLOYEE (EMPLOYEE_NAME,EMPLOYEE_DEPARTMENT,EMPLOYEE_DESIGNATION,EMPLOYEE_LOCATION,EMPLOYEE_MOBILE_NO,EMPLOYEE_EMAIL_ID,EMPLOYEE_GENDER,EMPLOYEE_SALARY)
VALUES("Rakesh","WPS","Senior System Analyst","MUM","8899776655","rakesh@gmail.com","Male","43000");

INSERT INTO EMPLOYEE (EMPLOYEE_NAME,EMPLOYEE_DEPARTMENT,EMPLOYEE_DESIGNATION,EMPLOYEE_LOCATION,EMPLOYEE_MOBILE_NO,EMPLOYEE_EMAIL_ID,EMPLOYEE_GENDER,EMPLOYEE_SALARY)
VALUES("Nikhil","WPS","Manager WPS Dept","HYD","9877665544","nikhil@gmail.com","Male","58000");

INSERT INTO EMPLOYEE (EMPLOYEE_NAME,EMPLOYEE_DEPARTMENT,EMPLOYEE_DESIGNATION,EMPLOYEE_LOCATION,EMPLOYEE_MOBILE_NO,EMPLOYEE_EMAIL_ID,EMPLOYEE_GENDER,EMPLOYEE_SALARY)
VALUES("Raju","DEV","Developer Trainee","MUM","9088997700","raju@gmail.com","Male","100000");

INSERT INTO EMPLOYEE (EMPLOYEE_NAME,EMPLOYEE_DEPARTMENT,EMPLOYEE_DESIGNATION,EMPLOYEE_LOCATION,EMPLOYEE_MOBILE_NO,EMPLOYEE_EMAIL_ID,EMPLOYEE_GENDER,EMPLOYEE_SALARY)
VALUES("Barath","DEV","Developer","MUM","7860980987","barath@gmail.com","Male","125000");

INSERT INTO EMPLOYEE (EMPLOYEE_NAME,EMPLOYEE_DEPARTMENT,EMPLOYEE_DESIGNATION,EMPLOYEE_LOCATION,EMPLOYEE_MOBILE_NO,EMPLOYEE_EMAIL_ID,EMPLOYEE_GENDER,EMPLOYEE_SALARY)
VALUES("Vijay","DEV","Senior Developer","BLR","8760099887","vijay@gmail.com","Male","150000");

INSERT INTO EMPLOYEE (EMPLOYEE_NAME,EMPLOYEE_DEPARTMENT,EMPLOYEE_DESIGNATION,EMPLOYEE_LOCATION,EMPLOYEE_MOBILE_NO,EMPLOYEE_EMAIL_ID,EMPLOYEE_GENDER,EMPLOYEE_SALARY)
VALUES("Dilip","DEV","Architect","CHN","7207207207","dilip@gmail.com","Male","160000");

INSERT INTO EMPLOYEE (EMPLOYEE_NAME,EMPLOYEE_DEPARTMENT,EMPLOYEE_DESIGNATION,EMPLOYEE_LOCATION,EMPLOYEE_MOBILE_NO,EMPLOYEE_EMAIL_ID,EMPLOYEE_GENDER,EMPLOYEE_SALARY)
VALUES("Rakesh Mora","DEV","Manager Dev Dept","CHN","7302344678","rakesh@gmail.com","Male","175000");

INSERT INTO EMPLOYEE (EMPLOYEE_NAME,EMPLOYEE_DEPARTMENT,EMPLOYEE_DESIGNATION,EMPLOYEE_LOCATION,EMPLOYEE_MOBILE_NO,EMPLOYEE_EMAIL_ID,EMPLOYEE_GENDER,EMPLOYEE_SALARY)
VALUES("Aravind","TEST","Testing Trainee","CHN","9000123123","aravind@gmail.com","Male","90000");

INSERT INTO EMPLOYEE (EMPLOYEE_NAME,EMPLOYEE_DEPARTMENT,EMPLOYEE_DESIGNATION,EMPLOYEE_LOCATION,EMPLOYEE_MOBILE_NO,EMPLOYEE_EMAIL_ID,EMPLOYEE_GENDER,EMPLOYEE_SALARY)
VALUES("Rahul","TEST","Test Engineer","BLR","8796785678","rahul@gmail.com","Male","95000");

INSERT INTO EMPLOYEE (EMPLOYEE_NAME,EMPLOYEE_DEPARTMENT,EMPLOYEE_DESIGNATION,EMPLOYEE_LOCATION,EMPLOYEE_MOBILE_NO,EMPLOYEE_EMAIL_ID,EMPLOYEE_GENDER,EMPLOYEE_SALARY)
VALUES("Sai Teja","TEST","Senior Test Engineer","HYD","9008877112","saiteja@gmail.com","Male","98000");

INSERT INTO EMPLOYEE (EMPLOYEE_NAME,EMPLOYEE_DEPARTMENT,EMPLOYEE_DESIGNATION,EMPLOYEE_LOCATION,EMPLOYEE_MOBILE_NO,EMPLOYEE_EMAIL_ID,EMPLOYEE_GENDER,EMPLOYEE_SALARY)
VALUES("Mansoor","TEST","Senior Test Engineer","MUM","6789123450","mansoor@gmail.com","Male","98000");

INSERT INTO EMPLOYEE (EMPLOYEE_NAME,EMPLOYEE_DEPARTMENT,EMPLOYEE_DESIGNATION,EMPLOYEE_LOCATION,EMPLOYEE_MOBILE_NO,EMPLOYEE_EMAIL_ID,EMPLOYEE_GENDER,EMPLOYEE_SALARY)
VALUES("Prashanth","TEST","Manager Test Dept","PUNE","8881111333","prashanth@gmail.com","Male","124000");

INSERT INTO EMPLOYEE (EMPLOYEE_NAME,EMPLOYEE_DEPARTMENT,EMPLOYEE_DESIGNATION,EMPLOYEE_LOCATION,EMPLOYEE_MOBILE_NO,EMPLOYEE_EMAIL_ID,EMPLOYEE_GENDER,EMPLOYEE_SALARY)
VALUES("Sai Nani","SUPPORT","Support Trainee","HYD","9014314314","sainani@gmail.com","Male","60000");

INSERT INTO EMPLOYEE (EMPLOYEE_NAME,EMPLOYEE_DEPARTMENT,EMPLOYEE_DESIGNATION,EMPLOYEE_LOCATION,EMPLOYEE_MOBILE_NO,EMPLOYEE_EMAIL_ID,EMPLOYEE_GENDER,EMPLOYEE_SALARY)
VALUES("Kranthi","SUPPORT","Support Enginner","MUM","8978978960","kranthi@gmail.com","Male","70000");

INSERT INTO EMPLOYEE (EMPLOYEE_NAME,EMPLOYEE_DEPARTMENT,EMPLOYEE_DESIGNATION,EMPLOYEE_LOCATION,EMPLOYEE_MOBILE_NO,EMPLOYEE_EMAIL_ID,EMPLOYEE_GENDER,EMPLOYEE_SALARY)
VALUES("Laxmi","SUPPORT","Senior Support Engineer","CHN","9977663300","laxmi@gmail.com","Male","74000");

INSERT INTO EMPLOYEE (EMPLOYEE_NAME,EMPLOYEE_DEPARTMENT,EMPLOYEE_DESIGNATION,EMPLOYEE_LOCATION,EMPLOYEE_MOBILE_NO,EMPLOYEE_EMAIL_ID,EMPLOYEE_GENDER,EMPLOYEE_SALARY)
VALUES("Kiran","SUPPORT","Senior Support Engineer","PUNE","901236547","kiran@gmail.com","Male","78000");

INSERT INTO EMPLOYEE (EMPLOYEE_NAME,EMPLOYEE_DEPARTMENT,EMPLOYEE_DESIGNATION,EMPLOYEE_LOCATION,EMPLOYEE_MOBILE_NO,EMPLOYEE_EMAIL_ID,EMPLOYEE_GENDER,EMPLOYEE_SALARY)
VALUES("Mallesh","SUPPORT","Manager Support Dept","BLR","9010203040","mallesh@gmail.com","Male","90000");
